# Generated by Django 2.1.3 on 2019-12-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='img_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
